### ISSUE TITLE
一点问题

### ISSUE THREAD

**Issue by aimhabo** [zjc798719285/Mask_Yolo#1]
我在ubuntu16.04+anaconda2+pytorch0.3.0下有这个问题
需要在Loss.py等文件开头需要加上#coding=utf-8

**Comment by aimhabo** [comment]
另外有个问题，PersonTrainImage 是图像文件夹的话，PersonTrainMask、PersonBbox分别是啥？由Segmentation.csv+对应图片生成的二值图和外接矩形label么？
从def load_dataset(ImagePath, MaskPath, BboxPath):来看，image-mask-box是唯一对应关系。那么我一图多样本的数据集该怎么做呢？

**Comment by zjc798719285** [comment]
我这就自己玩的，现在效果也不好啊，就是想先语义分割，然后针对每一个前景像素回归box，最后得到的一个分割图像，一个box的列表。分别在原图和分割图上crop就能得到带有分割图像的box了。
